---
plugin: aws_ec2
#aws_access_key: <YOUR-AWS-ACCESS-KEY-HERE>
#aws_secret_key: <YOUR-AWS-SECRET-KEY-HERE>
#https://docs.ansible.com/ansible/latest/collections/amazon/aws/aws_ec2_inventory.html
#/opt/ansible/inventory/aws_ec2.yaml
#ansible-inventory -i /opt/ansible/inventory/aws_ec2.yaml --list | jq
keyed_groups:
  - key: tags
    prefix: tag
  - prefix: instance_type
    key: instance_type
  - key: placement.region
    prefix: aws_region
  - prefix: arch
    key: 'architecture'
