---
- name: Play for installing nginx server
  hosts: allservers
  become: yes
  become_user: root
  tasks:
  - name: Perform apt update
    shell: apt update
    tags:
    - update

  - name: Install nginx server
    shell: apt install -y nginx
    tags:
    - install

  - name: Start nginx service
    shell: service nginx start
    tags:
    - service
  tags:
  - nginx

- name: Play for creating adminuser
  hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Create users
    user:
     name: "pavan"
     state: "present"
     shell: "/bin/bash"
  tags:
  - users