---
- name: Installing mysql using ansible role
  hosts: privateservers
  become: yes
  become_user: root
  roles:
   - { role: geerlingguy.mysql }
  tasks:
  - name: Create a new database
    mysql_db: >
     name=myflixdb
     state=present
     login_user=root
    tags:
     - create  
  - name: Copy the sample data to tmp folder
    copy: >
     src=dump.sql
     dest=/tmp/dump.sql
    tags:
     - copy
  - name: Insert/Import sample data into database
    mysql_db: >
     name=myflixdb
     state=import 
     target=/tmp/dump.sql
    tags:
     - insert
